---
title: "Práctica 11: Anotación"
lang: es
date: today
execute: 
  output: true
  error: true
engine: knitr
bibliography: ../../doc/references.bib
language:
   title-block-published: "Última actualización:"
   section-title-references: "Bibliografía"
format:
   html:
      embed-resources: true
editor: 
  markdown: 
    wrap: 72
---

En esta práctica vamos a trabajar con los resultados de la anotación
estructural de la práctica anterior, y usaremos las proteínas del
cromosoma 4 de *Arabidopsis thaliana*, que esperamos que estén
codifcadas en los *contigs*.

## Modificación de los nombres de proteínas

Las proteínas de *Arabidopsis thaliana* descargadas en formato `FASTA`
tienen cabeceras demasiado largas, por lo que vamos a modificarlas para
que sea más fácil trabajar con ellas.

::: {.callout-note icon="false"}
### Ejercicio 1

Sabiendo que una forma de hacerlo es la siguiente, incluye la orden en
un bloque de Bash de tu documento de Quarto de tal manera que el archivo
de entrada esté en tu carpeta `data` y el de salida en la misma carpeta
de trabajo de la práctica actual, y además, que sólo se ejecute si el
archivo de salida `proteinas.fasta` no existe.

```{bash}
if [ ! -e proteinas.fasta ]; then
   awk '(/^>/){split($1, A, /\|/); print ">" A[2]}(/^[^>]/){print $0}' ../../data/uniprotkb_proteome_UP000006548_AND_prot_2026_04_28.fasta > proteinas.fasta
   fi
```
:::

## Análisis de los resultados de `RepeatModeler`

`RepeatModeler` fue ejecutado de la siguiente manera:

```{bash}
#| eval: false
# Paso previo para convertir el ensamblaje en una base de datos de BLAST:
BuildDatabase -name At4 ../2026-04-16/asm1/At4.fa

RepeatModeler -database At4 -threads 6 >& run.log
```

::: {.callout-note icon="false"}
### Ejercicio 2

Explora los resultados de `RepeatModeler` y trata de contestar las
preguntas siguientes.

1.  ¿Cuántas familias de elementos transponibles se han encontrado?

    `grep -c "^>" consensi.fa.classified`

    Hay 24 familias de elementos transponibles.

2.  ¿Cuánto duró la ejecución del programa?

    01:02:16

3.  ¿Cuál dirías que es el archivo de salida más importante?

    `consensi.fa.classified` tiene todas las secuencias consenso de
    elementos transponibles e información de cada familia
:::

## Suavizar la máscara

`RepeatMasker` fue ejecutado así:

```{bash}
#| eval: false
RepeatMasker -lib At4-families.fa -dir RM01 -gtf ../../data/At4.fa
```

Los resultados de `RepeatMasker` de los que disponemos tienen una
máscara dura, pero para trabajar con `GALBA` es recomendable partir de
un ensamblaje con máscara suave, que permite distinguir los elementos
repetitivos (n minúscula) de los elementos transponibles (N mayúscula).
Para convertir la máscara dura en una más suave vamos a usar `bedtools`.

::: {.callout-note icon="false"}
### Ejercicio 3

1.  Instala el programa `bedtools` siguiendo las instrucciones oportunas
    para tu sistema en la [página oficial](#0)

2.  Utiliza el ensamblaje original como archivo FASTA de entrada y el
    archivo `GFF` que ha producido `RepetaMasker` como coordenadas de
    las regiones a enmascarar. Lee el manual de `bedtools maskfasta` [en
    este enlace](#0) y genera el ensamblaje con máscara suave llamado
    `At4.soft.fa`.

    ```{bash}
    if [ ! -e At4.soft.fa ]; then
        bedtools maskfasta \
        -fi ../2026-04-21/asm1/At4.fa \
        -bed RM01/At4.fa.out.gff \
        -fo At4.soft.fa \
        -soft
    fi
    ```
:::

## GALBA

Para ejecutar `GALBA` es necesario crear unas variables que le indiquen
dónde puede encontrar los ejecutables, que es recomendable indicar al
inicio del bloque para facilitar la reproducibilidad.

::: {.callout-note icon="false"}
### Ejercicio 4

Incluye en tu documento de Quarto un bloque de código (pero no
ejecutable, con la opción `eval: false`) como el anterior, donde los
*caminos* TSERBA y a MINIPROTHINT se correspondan con tu propia carpeta
`bin`, aunque no los tengas instalados.

```{bash}
#| eval: false
export TSEBRA_PATH=/home/anacanellesmarti/bin/TSEBRA/bin/
export MINIPROTHINT_PATH=/home/anacanellesmarti/bin/miniprothint/

galba.pl --species="Arabidopsis thaliana" \
         --genome=At4.soft.fa \
         --prot_seq=proteinas.fasta
```
:::

::: {.callout-note icon="false"}
### Ejercicio 5

Échales un vistazo a los archivos de salida de GALBA y trata de sacar
algo en claro.

Uno de los archivos de salida de GALBA/archive tiene en el nombre
`augustus`, por lo que podemos ssuponer que sirve para predecir genes en
secuencias genómicas de eucariotas.

Además, hay otros archivos llamados `train`, lo que significa que el
programa ha sido entrenado para que dé las secuencias

En GALBA/species hay una capteta de *A. Thaliana*, por lo que las
secuencias son de esa especie.

El archivo prinicpal es galba.gtf

No aparecen UTR por que no hay transcritos de RNA-seq, si le damos
porteinas no tienen evidencia de dónde empieza el gen, solo sabe la
región codificante.
:::
