---
title: "Práctica 11: Anotación"
format: 
    html:
      embed-resources: true
---

## Modificación de los nombres de proteínas

::: callout-note
## Ejercicio 1

Sabiendo que una forma de hacerlo es la siguiente, incluye la orden en un bloque de Bash de tu documento de Quarto de tal manera que el archivo de entrada esté en tu carpeta `data` y el de salida en la misma carpeta de trabajo de la práctica actual, y además, que sólo se ejecute si el archivo de salida `proteinas.fasta` no existe.

```{bash}
if [ ! -e proteinas.fasta ]; then
   awk '(/^>/){split($1, A, /\|/); print ">" A[2]}(/^[^>]/){print $0}' ../../data/uniprotkb_proteome_UP000006548_AND_prot_2026_04_28.fasta > proteinas.fasta
   fi
```
:::

## Análisis de los resultados de `RepeatModeler`

::: callout-note
## Ejercicio 2

Explora los resultados de `RepeatModeler` y trata de contestar las preguntas siguientes.

1.  ¿Cuántas familias de elementos transponibles se han encontrado?

    `grep -c "^>" consensi.fa.classified`

    24

2.  ¿Cuánto duró la ejecución del programa?

    01:02:16

3.  ¿Cuál dirías que es el archivo de salida más importante?

    `consensi.fa.classified` tiene todas las secuencias consenso de elementos transponibles e información de cada familia
:::

## Suavizar la máscara

::: callout-note
## Ejercicio 3

1.  Instala el programa `bedtools` siguiendo las instrucciones oportunas para tu sistema en la [página oficial](#0)

2.  Utiliza el ensamblaje original como archivo FASTA de entrada y el archivo `GFF` que ha producido `RepetaMasker` como coordenadas de las regiones a enmascarar. Lee el manual de `bedtools maskfasta` [en este enlace](#0) y genera el ensamblaje con máscara suave llamado `At4.soft.fa`.

    ```{bash}
    if [ ! -e At4.soft.fa ]; then
        bedtools maskfasta \
        -fi ../2026-04-21/asm1/At4.fa \
        -bed RM01/At4.fa.out.gff \
        -fo At4.soft.fa \
        -soft
    fi
    ```
:::

## GALBA

::: callout-note
## Ejercicio 4

Incluye en tu documento de Quarto un bloque de código (pero no ejecutable, con la opción `eval: false`) como el anterior, donde los *caminos* TSERBA y a MINIPROTHINT se correspondan con tu propia carpeta `bin`, aunque no los tengas instalados.

```{bash}
#| eval: false
no sé
```
:::

::: callout-note
## Ejercicio 5

Échales un vistazo a los archivos de salida de GALBA y trata de sacar algo en claro.
:::

::: callout-note
## Ejercicio 6

Si quieres, puedes intentar instalar GALBA en tu ordenador, tomando nota de las dificultades con las que te encuentras.
:::
