---
title: "Práctica 1. Nociones de Bash y alineamientos básicos"
lang: es
date: today
execute: 
  output: true
  error: true
engine: knitr
bibliography: ../../references.bib
language:
   title-block-published: "Última actualización:"
   section-title-references: "Bibliografía"
format:
   html:
      embed-resources: true
editor: 
  markdown: 
    wrap: 72
---

# Preparación

Hacen falta los programas `needle` y `water` de
[EMBOS](http://emboss.open-bio.org/), el programa
[`exonerate`](https://www.animalgenome.org/bioinfo/resources/manuals/exonerate/index.html)
[@Slater2005], y el programa
[`muscle`](https://www.drive5.com/muscle5/)[@Edgar2022]. Para la
descarga automática de secuencias usaremos el programa `wget`. En
sistemas operativos basados en Debian, seguramente se pueden instalar
los cinco programas así (con privilegios administrativos):

```         
apt install emboss exonerate wget muscle
```

usar el sudo antes

# Objetivos

1.  Practicar los comandos básicos de Bash.
2.  Generar la estructura del cuaderno de prácticas.
3.  Realizar algunos alineamientos básicos.

# Comandos básicos

| Comando | Función |
|------------------------------------|:-----------------------------------|
| pwd | Conocer la dirección absoluta del directorio actual. ¿Dónde estoy? |
| cd .. | Cambiar al directorio superior (volver al directorio anterior) |
| cd a | Entrar en el directorio "a" |
| cp a b | Crear una copia "b" del archivo "a" |
| mv a b | Renombrar el archivo "a" como "b" |
| mkdir a | Crear el directorio "a" |
| rm a | Eliminar el *archivo* "a" |
| rm -r a | Eliminar el *directorio* "a" y su contenido |
| touch a | Crear el archivo vacío "a" o actualizar su fecha de consulta si ya existía |
| ls |  |
| ls -lh | no sé muy bien qué hace pero te dice todo lo que tienes con administradores y cosas raras |
| ls -1 | Mostrar el contenido de la carpeta |
| cd \~ | Volver a casa |

directorio = carpeta

Que las subcarpetas de resultados tengan de nombre la fecha en que se
empieza un análisis, por que nunca sabes cómo vas a acabar.

Normalmente las carpetas son "doc", "data" y "results". doc tiene
referencias, facturas, bibliografía (bib) y cosas; data son los datos y
results es el que tiene las subcarpetas.

Además tener un archivo que sirva de índice y se suele llamar "README".
Tiene la extensión .md (markdown) para convertirlo a html. Este archivo
no está dentro de las subcarpetas, sino al nivel principal.

Dentro de cada carpeta de análisis debería haber un script que cuando se
ejecute se regeneren los resultados (README.qmd).

cp y mv sirven para copiar o mover un archivo a otro sitio. Se debería
poner todas las carpetas dentro de las que está y a donde va pero se
puede usar el tabulador (completar los nombres de las carpetas sin tener
que escribirlo todo). También se puede hacer con ../../ etc y cada .. es
un nivel que se sube. Esto es un path relativo porque depende de dónde
estas tiene un sentido u otro.

::: {.callout-tip title="Consejo"}
Amplía la tabla modificando el documento fuente.
:::

::: {.callout-note icon="false"}
## Ejercicio 1

Escoge un lugar adecuado en el árbol de directorios de tu ordenador para
crear la carpeta que contendrá tu cuaderno de prácticas, en el cual
incluirás tu propia versión de este primer guión. El *cuaderno* será una
**carpeta** entera. Dale un nombre adecuado y genera esta estructura en
su interior usando los comandos de Bash que has aprendido:

```         
├── data
├── doc
└── results
    ├── 2026-01-29
    │   └── README.Qmd
    ├── 2026-02-03
    ├── 2026-02-10
    ├── 2026-02-17
    ├── 2026-02-24
    ├── 2026-03-03
    ├── 2026-03-10
    ├── 2026-03-24
    ├── 2026-03-31
    ├── 2026-04-15
    ├── 2026-04-21
    ├── 2026-04-28
    └── 2026-05-05
```
:::

Abrir emboss:

```         
conda activate emboss
```

Cerrar: :

```         
conda deactivate
```

Si tuviesemos muchas más secuencias se usa muscle. Hay un paquete de
algo que tiene la función browse que nos permite ver el resultado en el
html. es alineamiento de proteínas.

# Alineamiento de pares de secuencia

En los enlaces siguientes encontrarás las secuencias descritas a
continuación:

-   [HumanChr17](https://rest.ensembl.org/sequence/region/human/17:63832000..63843000:1)
    Un fragmento del cromosoma 17 humano.
-   [ChimpChr17](https://rest.ensembl.org/sequence/region/chimpanzee/17:63309800..63321000:1)
    Un fragmento del cromosoma 17 de chimpancé, homólogo al anterior.
-   [HumanSMARCD2](https://www.ebi.ac.uk/ena/browser/api/fasta/AAI36323.1)
    Tránscrito del gen SMARCD2 humano.
-   [ChimpSMARCD2](https://www.ebi.ac.uk/ena/browser/api/fasta/PNJ01291.1)
    Tránscrito del gen SMARCD2 de chimpancé.

El objetivo es alinear los tránscritos a sus respectivos fragmentos
genómicos y comprobar que el alineamiento predice correctamente la
estructura de intrones y exones del gen. Si las herramientas de
[EMBOSS](http://emboss.open-bio.org/) están instaladas, podemos usar los
programas
[`needle`](http://emboss.open-bio.org/rel/rel6/apps/needle.html) o
[`water`](http://emboss.open-bio.org/rel/rel6/apps/water.html) para
realizar el alineamiento desde la linea de órdenes mediante los
algoritmos de Needleman-Wunsch o de Smith-Waterman, respectivamente.
Puedes consultar la ayuda completa de estas herramientas ejecutando
`needle -help -verbose` o `water -help -verbose`. Las órdenes siguientes
descargan dos de las secuencias y las alinean con `needle`, a modo de
ejemplo. El resultado del alineamiento debería guardarse en un archivo
en formato de texto.

```{bash}
#| eval: false
# Sólo queremos ejecutar el código si los resultados no
# están ya disponibles, es decir, si el archivo de salida no existe.
if [ ! -e aln1.txt ]; then
   # Sólo descargaremos las secuencias, si no están ya descargadas.
   if [ ! -e HumanSMARCD2.fa ]; then
      # Con la opción "-O" (letra mayúscula, no número cero) indicamos
      # el nombre del archivo donde queremos guardar la secuencia.
      wget -O HumanSMARCD2.fa  https://www.ebi.ac.uk/ena/browser/api/fasta/AAI36323.1;
   fi
   if [ ! -e HumanChr17.fa ]; then
      wget -O HumanChr17.fa https://rest.ensembl.org/sequence/region/human/17:63832000..63843000:1?content-type=text/x-fasta
   fi
   # Utilizamos el carácter "\" para que Bash ignore el salto de línea
   # y poder distribuir los argumentos y opciones en más de una línea.
   needle -asequence HumanChr17.fa \
          -bsequence HumanSMARCD2.fa \
          -gapopen 15.0 \
          -gapextend 0.5 \
          -auto \
          -outfile aln1.txt
fi
```

Manejar EMBOSS no es tan importante, hay paquetes de R que lo hacen.
wget para descargar las secuencias de internet y needle para alinearlas.

ejecucion condicional: las condiciones se pueden encajar. si no existe
un archivo que se llame de una manera entonces ejecuta todo lo que pone.

desde que empieza if hasta que termina fi. la exclamación significa no.

if \[ ! -e aln1.txt\]; then algo. si no existe el archivo que se llama
de esa manera, entonces descargar con wget, y se le dice que el output
se envie a un sitio con ese nombre (-O) desde la web que pone.

Una vez nos aseguramos que tenemos los dos archivos los alineamos. El \\
es para ignorar el carácter siguiente (salto de linea en este caso). Ahí
se ponen los argumentos que utiliza needle, que implementa un algoritmo
de alineación de dos secuencias. Si conseguimos alinearlo obtenemos un
archivo de txt. Deja bastante que desear. Los argumentos de alineamiento
siempre dan un resultado, aunque no sea correcto.

```         
head -5 (nombre archivo secuencia)
```

Muestra las primeras lineas de la secuencia para comprobar que se ha
descargado correctamente.

(aln1.txt alineamiento de humano con needle; aln2.txt alineamiento de
humano con water)

::: {.callout-note icon="false"}
## Desafíos

0.  Lee detenidamente las órdenes y los comentarios y asegúrate de
    entenderlos.
1.  Si al ejecutarlas aparece algún mensaje de error, léelo y corrige el
    error.
2.  Lee la ayuda del programa `needle` e intenta ajustar los parámetros
    para obtener un alineamiento más convincente.
3.  Prueba el programa `water`, para que el alineamiento sea local.
4.  Intenta guardar el alineamiento en formato FASTA.
5.  Alinea también el tránscrito de SMARCD2 de chimpancé a su cromosoma.
6.  Alinea también los dos fragmentos cromosómicos.
:::

Alineamiento chimpancé:

```{bash}
if [ ! -e aln2.txt ]; then
   if [ ! -e ChimpSMARCD2 ]; then
      wget -O ChimpSMARCD2.fa  https://www.ebi.ac.uk/ena/browser/api/fasta/PNJ01291.1;
   fi
   if [ ! -e ChimpChr17.fa ]; then
      wget -O ChimpChr17.fa https://rest.ensembl.org/sequence/region/chimpanzee/17:63309800..63321000:1
   fi
   needle -asequence ChimpChr17.fa \
          -bsequence ChimpSMARCD2.fa \
          -gapopen 15.0 \
          -gapextend 0.5 \
          -auto \
          -outfile aln2.txt
fi
```

Para alinear tránscritos o incluso proteínas a un genoma de referencia,
es mejor usar el programa `exonerate` [@Slater2005], que puede aplicar
los parámetros más adecuados para este tipo de tarea. Puedes leer la
documentación de `exonerate` mediante las órdenes `man exonerate` o
`exonerate --help`. También existe [documentación online sobre este
programa](https://www.animalgenome.org/bioinfo/resources/manuals/exonerate/index.html).
En el bloque siguiente repetimos el mismo alineamiento que antes, con
`exonerate`.

```{bash}
#| eval: true
#| output: true
#| error: true

if [ ! -e HumanSMARCD2.fa ]; then
   wget -O HumanSMARCD2.fa https://www.ebi.ac.uk/ena/browser/api/fasta/AAI36323.1
fi
if [ ! -e HumanChr17.fa ]; then
   wget -O HumanChr17.fa \
      https://rest.ensembl.org/sequence/region/human/17:63832000..63843000:1?content-type=text/x-fasta
fi
exonerate --model est2genome HumanSMARCD2.fa HumanChr17.fa
```

En este caso, el alineamiento resultante no se ha enviado a un archivo,
sino al *standard output*, que Quarto recoge y presenta en este mismo
documento. Por eso, no hemos condicionado la ejecución.

exonerate es mucho más inteligente, y en sus argumentos puedes decirle
el modelo de argumento que estas alineando. Alineamos un mRNA sin
intrones a un trozo de cromosoma. El alineamiento es muy pobre, le
tenemos que decir al algoritmo que no hay intrones para que compare por
trozos.

est2genome es lo que le dice al algoritmo que ya no hay intrones para
que pueda alinear las secuencias por fragmentos (man exonerate para ver
todos los tipos de algoritmos).

(aln3.txt alineamiento de humano con exonerate)

::: {.callout-note icon="false"}
## Desafío

¿Cómo puedes enviar el resultado de `exonerate` a un archivo?
:::

El resultado aparece en el terminal, y se salta las secuencias de
intrones. Para que el alineamiento salga en pantalla, no le decimos a
exonerate que guarde el archivo y así sale en el programa. Para guardar
el alineamiento en un archivo escribimos \> (nombre del archivo) detrás
del comando de alineación y así redirigimos el resultado.

# Apéndice. Alineamientos múltiples

Un programa muy popular para alineamiento de múltiples secuencias es
[`muscle`](https://drive5.com/muscle/) [@Edgar2022]. Suponiendo que está
instalado, vamos a probarlo con una colección de secuencias que
pertenecen a la familia
[PF00009](https://www.ebi.ac.uk/interpro/entry/pfam/PF00009/):

```{bash}
if [ ! -e PF00009.fa ]; then
   wget -O PF00009.fa https://raw.githubusercontent.com/rcedgar/balifam/refs/heads/main/balifam100/in/PF00009.100
fi

if [ ! -e PF00009.afa ]; then
   muscle -align PF00009.fa -output PF00009.afa
fi
```

Si tuviesemos muchas más secuencias se usa muscle. Hay un paquete de
algo que tiene la función browse que nos permite ver el resultado en el
html. es alineamiento de proteínas. (lo he exportado como .txt porque no
podía verlo)

(PF00009.afa y .txt alineamiento de secuencias múltiples por muscle)

Para visualizar el alineamiento, podemos usar la función `BrowseSeqs()`,
del paquete `DECIPHER` en el entorno de R. Esta función nos permite
enviar el alineamiento a un archivo HTML, que puede abrirse en una
ventana nueva. Si estamos compilando un documento HTML, podemos
incorporar el alineamiento en el mismo documento mediante la función
`includeHTML()` del paquete `htmltools`, al precio de aumentar
considerablemente su tamaño.

```{r}
#| messages: false
#| warning: false

library('htmltools')
library('DECIPHER')
PF00009 <- readAAStringSet('PF00009.afa')
BrowseSeqs(PF00009, htmlFile = 'PF00009.html', openURL = FALSE)
includeHTML('./PF00009.html')
```

# Bibliografía
